flask/app/flaskr/basic_bp/models.py
from flask import current_app
from ..app import db
import secrets

class User(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    username = db.Column(db.Text(), index=True)
    password = db.Column(db.Text(), index=True)
    role = db.Column(db.Text())
    description = db.Column(db.Text())

def populate():
    if User.query.filter_by(id=1).first():
        return

    user = User(username="admin", password=current_app.config.get("ADMIN_PASSWORD"), role="admin")
    db.session.add(user)
    db.session.commit()

flask/app/flaskr/models.py
from flaskr.basic_bp import models

flask/app/flaskr/basic_bp/forms.py
from flask_wtf import Form
from wtforms import TextField, SubmitField, TextAreaField, PasswordField

class loginform(Form):
    username = TextField("username")
    password = PasswordField("password")
    submit = SubmitField("go!")

flask/app/flaskr/__init__.py
from flaskr.app import (
    create_app, db
)

flask/app/flaskr/app.py
from flask import Flask
import logging
import os
from flask_sqlalchemy import SQLAlchemy

class ConfigClass(object):
    # Flask settings
    # DEBUG = True
    SECRET_KEY                      = 'fuckyouandyoursecretkey'
    SQLALCHEMY_DATABASE_URI         = 'postgresql+psycopg2://adminisbestusername:hunter2isbestpassword@db:5432/magicdatabase'
    SQLALCHEMY_ECHO                 = True
    FLAG = os.getenv("FLAG", "flag{noflaglol}")
    HOST = os.getenv("HOST", "http://localhost")
    ADMIN_PASSWORD = os.getenv("ADMIN_PASSWORD", "memes_make_dreams")

db = SQLAlchemy()

def register_models(app):
    from .basic_bp import models

    with app.app_context():
        db.init_app(app)
        db.create_all()

        models.populate()

def register_blueprints(app):
    from .basic_bp import app as basic_bp
    app.register_blueprint(basic_bp)

def create_app():
    app = Flask(__name__)
    app.config.from_object(__name__ + '.ConfigClass')

    register_models(app)
    register_blueprints(app)

    return app

flask/app/flaskr/basic_bp/__init__.py
from flask import Blueprint

app = Blueprint('app',
    __name__,
    template_folder='templates',
    static_folder='static')

from . import views

flask/app/flaskr/basic_bp/views.py
from flask import render_template, request, redirect, current_app, Flask, flash, url_for, session
import hashlib
import time
from multiprocessing import Process
from flaskr.app import db
from . import app
from . import forms
from . import horseman
from .models import User

@app.route("/profile", methods=["GET", "POST"])
def profile():
    cur_user = None
    print("\n".join("%s: %s" % (k, v) for k, v in request.cookies.items()))
    if request.cookies.get("flag", "") == current_app.config.get("FLAG"):
        cur_user = User.query.filter_by(username="admin").first()

    if not cur_user:
        if not session.get("user"):
            flash("Please log in")
            return redirect(url_for("app.profile"))
        cur_user = User.query.filter_by(username=session['user']).first()

    if request.method == "POST":
        description = request.form.get("description", "")
        cur_user.description = description
        db.session.add(cur_user)
        db.session.commit()
        print("User: %s description updated to: %s" % (cur_user.username, cur_user.description))
        flash("Profile updated")
    return render_template("profile.html", user = cur_user)


@app.route("/logout")
def logout():
    session['user'] = None
    session.clear()
    return redirect(url_for("app.login"))

@app.route("/contact", methods=["GET", "POST"])
def contact():
    if request.method == "POST":
        url = request.form.get("url", "")
        p = Process(
            target=horseman.xss_get,
            args=(url, current_app.config.get("HOST"), "flag", current_app.config.get("FLAG"),))
        p.start()
        flash("Your URL is being visited")
    return render_template("contact.html")


@app.route('/', methods=['GET', 'POST'])
def login():
    if session.get("user"):
        flash("you are already logged in")
        return(redirect(url_for("app.profile")))


    if request.method == 'POST':
        username = request.form.get("username")
        password = request.form.get("password")


        if not username or not password:
            flash("Please have enter both a username and password")
            return render_template("register.html")

        cur_user = User.query.filter_by(username = username, password = password).first()
        if not cur_user:
            flash("Invalid username and password")
            return render_template("login.html")

        session['user'] = cur_user.username
        flash("Login successful")
        return redirect(url_for("app.profile"))

    return render_template("login.html")

@app.route('/register', methods=['GET', 'POST'])
def register():
    if session.get("user"):
        flash("you are already logged in")
        return(redirect(url_for("app.profile")))

    if request.method == 'POST':
        username = request.form.get("username")
        password = request.form.get("password")

        if not username or not password:
            flash("Please have both a username and password")
            return render_template("register.html")

        # check existence of username
        check_user = User.query.filter_by(username = username).all()
        if check_user:
            flash("Username already registered")
            return render_template("register.html")

        new_user = User(username=username, password=password, role='peasant')
        db.session.add(new_user)
        db.session.commit()

        flash("New user registered")
        return redirect(url_for("app.login"))

    return render_template("register.html")

flask/app/flaskr/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>goodestofdoggos</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <style>
        hr { border-color: #cccccc; margin: 0; }
        .no-margins { margin: 0px; }
        .with-margins { margin: 10px; }
        .col-centered { float: none; margin: 0 auto; }
    </style>

    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
    <link href="{{url_for("static", filename="styles.css")}}" rel="stylesheet">
  </head>

  <body>
    <div class="container mb-5">
      <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
          <div class="col-4 pt-1">
            <a class="text-muted" href="{{url_for("app.profile")}}">profile</a>
            <a class="text-muted" href="{{url_for("app.contact")}}">contact</a>
          </div>
          <div class="col-4 text-center">
           <a class="blog-header-logo text-dark" href="{{url_for("app.login")}}">awesome login</a>
          </div>
          <div class="col-4 d-flex justify-content-end align-items-center">
            <a class="btn btn-sm btn-outline-secondary mr-3" href="{{url_for("app.logout")}}">Logout</a>
            <a class="btn btn-sm btn-outline-secondary mr-3" href="{{url_for("app.login")}}">Login</a>
            <a class="btn btn-sm btn-outline-secondary" href="{{url_for("app.register")}}">Sign up</a>
          </div>
        </div>
      </header>
    </div>

    <div id="main-div" class="container mb-3">
    {# One-time system messages called Flash messages #}
    {% block flash_messages %}
        {%- with messages = get_flashed_messages(with_categories=true) -%}
            {% if messages %}
                {% for category, message in messages %}
                    {% if category=='error' %}
                        {% set category='danger' %}
                    {% elif category == "message" %}
                        {% set category="primary" %}
                    {% endif %}
                    <div class="alert alert-{{category}}">{{ message|safe }}</div>
                {% endfor %}
            {% endif %}
        {%- endwith %}
    {% endblock %}
    </div>

    <main role="main" class="container mb-5">
    {% block main %}{% block content %}{% endblock %}{% endblock %}
    </main><!-- /.container -->

    <footer class="blog-footer">
      <p>Blog template built for <a href="https://getbootstrap.com/">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  </body>
</html>